/*
 * NetPay.java
 * Author:  Aaron Shurley
 * Submission Date:  2/2/2021
 *
 * Purpose: The purpose of this program is to calculate the net pay, generated by 
 * given hours worked per week.
 *
 * Statement of Academic Honesty:
 *
 * The following code represents my own work. I have neither
 * received nor given inappropriate assistance. I have not copied
 * or modified code from any source other than the course webpage
 * or the course textbook. I recognize that any unauthorized
 * assistance or plagiarism will be handled in accordance with
 * the University of Georgia's Academic Honesty Policy and the
 * policies of this course. I recognize that my work is based
 * on an assignment created by the Department of Computer
 * Science at the University of Georgia. Any publishing
 * or posting of source code for this assignment is strictly
 * prohibited unless you have written consent from the Department
 * of Computer Science at the University of Georgia.  
 */

import java.util.Scanner;

public class NetPay {

	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);

		System.out.print("Hours per Week: \t");
		double hours = input.nextDouble();

		double gross = hours * 7.25;
	    double federal = ((gross * 10) / 100);
	    double state = ((gross * 4.5) / 100);
	    double social = ((gross * 6.2) / 100);
	    double medicare = ((gross * 1.45) / 100);
	    double deduction = (federal + state + social + medicare );
	    double net = (gross - deduction );

	    System.out.println("Gross Pay: \t\t" + gross);
	    System.out.println("Net Pay: \t\t" + net);
	    System.out.println(" ");
	    System.out.println("Deductions");
	    System.out.println("Federal: \t\t" + federal );
	    System.out.println("State: \t\t\t" + state);
	    System.out.println("Social Security: \t" + social);
	    System.out.println("Medicare: \t\t" + medicare);

	    input.close();


	}

}

	
	
